### ISSUE TITLE
😱😱😱😱😱😱😱😱

### ISSUE THREAD

**Issue by kkharji** [jbyuki/monolithic.nvim#1]
@jbyuki this is soooo smart!!! :star_struck: 

What if we can also write files, auto refresh content if files changes :D 

cc @tjdevries, @Conni2461 is this crazy idea?

**Comment by jbyuki** [comment]
Probably not a bad idea 😉 
Feel free to fork, pull request, make your own version,... the idea is public domain.

**Comment by jbyuki** [comment]
We could even think of a file explorer with inline content.

There is issues that I need to figure out first though.
For example, how to properly syntax highlight multiple files within a single buffer.
Vim is not playing nicely here.

**Comment by tjdevries** [comment]
@jbyuki perhaps some extensions to tree sitter would be good.

It can already do embedded parsers. Maybe we can add ext mark ranges as owned by a tree sitter highlighter.

**Comment by tjdevries** [comment]
Perhaps I will play with an idea similar to this. I think using ext marks you can do impressive control over the areas.

I am doing a similar concept right now for a go test manager.
