### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by MooersLab** [jbyuki/monolithic.nvim#3]
Your github rep path conflicts with the Plug command in the README file.
One uses monolithic.nvim and the other uses monolithic.vim.

https://github.com/jbyuki/monolithic.nvim.git

The output from using PlugUpdate:

```vim
x monolithic.vim:
    Cloning into '/Users/blaine/.config/nvim/plugged/monolithic.vim'...
    remote: Repository not found.
    fatal: repository 'https://github.com/jbyuki/monolithic.vim.git/' not found
```

**Comment by jbyuki** [comment]
That's a mistake on my part. The instruction is incorrect in the README. I will correct it asap. You're the first one to notice it, thanks for the issue!
